### ISSUE TITLE
Shuffle choices in multiple choice challenges

### ISSUE THREAD

**Issue by bocharsky-bw** [knpuniversity/activity-runner#9]
What about shuffle choices each time when page reload?
Now I can easily make cheat sheets with correct answer :)

**Comment by weaverryan** [comment]
But it's pretty easy just to click all of the answers until you find the right one now too ;). The only issue I see is that sometimes it makes most sense to have answer be the last one - like https://github.com/knpuniversity/oo/pull/2/files#diff-b84eaa8eed7177b027d118207e5c9048R57

**Comment by bocharsky-bw** [comment]
Yep, you're right. Maybe it's better to leave it as is. 

Anyway, we are not to do some serious examinations on KnpU with time and correct answers limits )

**Comment by weaverryan** [comment]
@bocharsky-bw that's might thought too - not really serious exams. Like with coding, we *give* you the answer :)
